### ISSUE TITLE
File Seeks With client.cat

### ISSUE THREAD

**Issue by amiller68** [ferristseng/rust-ipfs-api#103]
Hi,
I want to implement File Seeks with client.cat. For example, I'd like to request a range of bytes from an endpoint rather than the whole file.
I know this is possible with js-ipfs, and probably could be implemented by incorporating a 'range' header in the client's request to an endpoint.
Could anyone either offer me a way to do this with the repository as is or lay out steps for implementing this? I am new to Rust and not sure where to start looking.

**Comment by SionoiS** [comment]
Hi!

First you would have to add more option to the request.

https://github.com/ferristseng/rust-ipfs-api/blob/master/ipfs-api-prelude/src/request/cat.rs
https://docs.ipfs.io/reference/kubo/rpc/#api-v0-cat

In this case I don't think streaming progress would work but you might want to check yourself.

Then write some tests for it I guess. Sorry can't be more helpful it's been some time.

**Comment by amiller68** [comment]
> In this case I don't think streaming progress would work but you might want to check yourself.

What do you mean by that?

**Comment by amiller68** [comment]
Also, where are relevant tests defined?

**Comment by amiller68** [comment]
Working on this here: https://github.com/banyancomputer/rust-ipfs-api

**Comment by SionoiS** [comment]
@amiller68 I would not change the name of the request. Instead make the options.. well optional.

Check the IPFS docs it tells you what arguments are required or not.

**Comment by amiller68** [comment]
@SionoiS I'm v new to Rust but my understanding is creating a new function declaration for optional arguments is not atypical/a technique that is featured in the code I forked (e.g. files_read vs files_read_with_options, ls vs ls_with_options). Do you think it would help to redeclare `cat_bytes` as ``cat_with_options` or something?

**Comment by amiller68** [comment]
Other than that my Doc tests pass and independently tested the implementation in a separate repo
