### ISSUE TITLE
Connection Pooling is Disabled by Default for the Hyper Implementation

### ISSUE THREAD

**Issue by mrd0ll4r** [ferristseng/rust-ipfs-api#132]
Hello,

by default, the hyper backend disables connection pooling [here](https://github.com/ferristseng/rust-ipfs-api/blob/master/ipfs-api-backend-hyper/src/backend.rs#L56). This is suboptimal for two reasons:
1. Performance: Performing multiple requests with the same client will open a new connection for each request, which is slow and wasteful.
2. Long-running programs using the same client with many requests exhaust the port space of the host. This manifests in errors like this
```
hyper client error `error trying to connect: tcp connect error: Cannot assign requested address (os error 99)`
```

Alternatively, I'm looking at using the `actix` client, but it's not obvious how to enable `rustls` here.

**Comment by xianyu11111** [comment]
请问怎么初始化启动？
