### ISSUE TITLE
IPFS key API?

### ISSUE THREAD

**Issue by matthiasbeyer** [ferristseng/rust-ipfs-api#14]
Hey,

any plans to implement the IPFS Key API (basically what one can do with `ipfs key ...`) and IPNS name publishing/resolving?

Or is that already implemented and I am missing something?

**Comment by ferristseng** [comment]
Yeah, I plan on continuing work on this library. I just finished integrating it with my own project, so I have some time to revisit any new changes that were made in the interim.

It looks like I implemented `key gen`, and `key list` calls..but haven't gotten to `rm` and `rename` which might be new (?). (https://docs.rs/ipfs-api/0.4.0-alpha.1/ipfs_api/struct.IpfsClient.html#method.key_gen)

As for IPNS name publishing and resolving, it looks like they are not yet added. I can add them soon -- it shouldn't be too difficult.

**Comment by ferristseng** [comment]
Ok, I added these -- let me know if there are additional issues!
