### ISSUE TITLE
How can I add/get a raw buffer to/from IPFS?

### ISSUE THREAD

**Issue by MaiaVictor** [ferristseng/rust-ipfs-api#15]

**Comment by ferristseng** [comment]
There's a good example in the read me about how to do this. You'll probably want to take a look at these two methods:

  - https://docs.rs/ipfs-api/0.4.0-alpha.3/ipfs_api/struct.IpfsClient.html#method.add
  - https://docs.rs/ipfs-api/0.4.0-alpha.3/ipfs_api/struct.IpfsClient.html#method.get

**Comment by drozdziak1** [comment]
@ferristseng Why does `add` require a 'static lifetime? I've been trying to add a freshly-built non-static buffer to IPFS for at least an hour now.

**Comment by drozdziak1** [comment]
Nevermind, looks like I completely misunderstood how all this is meant to be used, Cursor<Vec<u8>> worked like a charm!
