### ISSUE TITLE
support for --hash and --raw-leaves arguments

### ISSUE THREAD

**Issue by brenzi** [ferristseng/rust-ipfs-api#26]
I've successfully used your examples, but what I'd like to do is the equivalent to 
```
> echo awesome test content > test.txt
> ipfs add --raw-leaves test.txt
zb2rhgCbaGmTcdZVRpZi3Z8CsdtAbFv7PRdRD9s6mKtef6LK9
> ipfs add --hash blake2b-256 test.txt
zCT5htke82ziqES2sZUP6MPR1EcC3DchZjbFuGeQcTfm16m5q5e8
```
Is that supported? I couldn't find anything in the docs.

**Comment by sameer** [comment]
Glad you got it working!
The way it is currently written, it is not supported -- the spec for the [Add request](https://github.com/ferristseng/rust-ipfs-api/blob/master/ipfs-api/src/request/add.rs) does not have any of the current parameters, so the [api add function](https://github.com/ferristseng/rust-ipfs-api/blob/master/ipfs-api/src/client.rs#L386) can't enable these.

There are several requests that need additional parameters like your use case, but most users would not need them. This might require adding a method like `add_with_raw_leaves` or even rewriting the api to be builder-style.

**Comment by ferristseng** [comment]
I think we could support this. There are already some ApiRequest implementations that have optional arguments. Maybe we could have an `add_with_options` that takes in an AddRequest that's populated with the optional arguments?

**Comment by sameer** [comment]
> The API actually supports it:

I agree, I was referring to the our implementation of it -- sorry for the confusion.

An add with options sounds like a good idea. The add request struct could implement default and the add function could just wrap the with options variant.

**Comment by sameer** [comment]
The [go IPFS API implementation of add](https://github.com/ipfs/go-ipfs-api/blob/master/add.go) uses functions that modify the request itself, and offers a few that are standard. Would that be something better to do here, since the api is technically v0?
