### ISSUE TITLE
async/await support?

### ISSUE THREAD

**Issue by daniel5151** [ferristseng/rust-ipfs-api#35]
Hey there!

I'd love to use this crate in a project of mine, but given that async/await is landing in stable on Nov 6th (just a few weeks from now), I can't bring myself to pull in a dependency that can't make use of the new syntax :disappointed: 

Are there any plans to migrate rust-ipfs-api over to the new async/await ecosystem? i.e: futures 0.3, tokio 0.2, and hyper 0.13? It looks like Actix is also working on async/await support (see https://github.com/actix/actix-net/issues/45)

I've taken a quick stab at using futures::compat with rust-ipfs-api, but unfortunately, hyper relies on having a tokio-0.1 runtime, and trying to run the compat'd futures on tokio 0.3 results in a runtime error.

**Comment by ferristseng** [comment]
Yeah, I definitely intend to keep everything up-to-date, but I'm also pretty stretched on time. At the very least, I think I'd prefer to hold off until hyper 0.13 is out alpha.

**Comment by delbonis** [comment]
Hyper 0.13.0 was just released the other day, any news on this?

**Comment by daniel5151** [comment]
On that note, [tokio-compat](https://github.com/tokio-rs/tokio-compat) is also out of alpha
