### ISSUE TITLE
Folder uploading

### ISSUE THREAD

**Issue by edfloreshz** [ferristseng/rust-ipfs-api#38]
Is there a way to upload entire folders?

I had to implement a recursive function to make this work and i was wondering if the API has a way to do this.

**Comment by sameer** [comment]
Yes, see https://github.com/ferristseng/rust-ipfs-api/commit/0cf5be505470b2bcaf837d93239283be1f9a4a1e

-------- Original Message --------

**Comment by edfloreshz** [comment]
Thank you! This is perfect!
