### ISSUE TITLE
PubSub

### ISSUE THREAD

**Issue by SionoiS** [ferristseng/rust-ipfs-api#55]
Hello!

I tried to send and receive messages locally but sending "hello world" I received "aGVsbG8gd29ybGQ=".
If I use the CLI ipfs pubsub sub <topic> It work as expected which makes me thing there's a bug somewhere.

I'll look around and see if I can fix it.

Otherwise great API!

**Comment by SionoiS** [comment]
Do we know what the returned json actually look like?

```
{
  "from": "",
  "data": "",
  "seqno": "",
  "topicIDs": [
    "",
    "",
    ""
  ],
  "XXX_unrecognized": [
      ???,
      ???
      ]
}
```
Something like that probably from what I can read [here]( https://github.com/ferristseng/rust-ipfs-api/blob/bbc48f85bac7565a11b77313f6aed7c44b9ebeed/ipfs-api/src/response/pubsub.rs#L29).

I tried decoding the data value with multibase and it failed so IDK...

Also, notice the = sign at the end, no multibase base have that char in their alphabet.

**Comment by SionoiS** [comment]
Ok I was wrong there's no bug...

I decoded the string but had to add a 'm' at the start to signify to multibase that it was base64 string.

**Comment by jcaesar** [comment]
I don't know... I think base64 is part of the format of the request, maybe the library should decode it.

**Comment by SionoiS** [comment]
> I don't know... I think base64 is part of the format of the request, maybe the library should decode it.

The [docs](https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-sub) tell us that it should be base64.

In reality it's base64 with padding. I used multibase crate with Base64Pad as setting.

+1 for having the lib decode it, it's a little confusing right now.

**Comment by Tails** [comment]
I had trouble here too, as did [this](https://stackoverflow.com/questions/54981069/how-to-parse-data-received-through-ipfs-python-api) StackOverflow poster. I was confused too. I started trying to decode the 'from' field but it kept failing. Until I realized that the decoded 'from' result is actually binary, and that the 'data' and 'seqno' were fine. This worked for me:

```rust
String::from_utf8(multibase::decode(format!("M{}", s)).unwrap().1)
```

**Comment by SionoiS** [comment]
I use this for the from field
```
let encoded = match response.from.as_ref()?;

let decoded = Base::decode(&Base::Base64Pad, encoded).expect("Decoding sender failed");

let cid = Cid::try_from(decoded).expect("CID from decoded sender failed");
```
and this for message
```
let encoded = response.data.as_ref()?;

let decoded = Base::decode(&Base::Base64Pad, encoded).expect("Decoding message failed");

let msg_str = match str::from_utf8(&decoded) {
        Ok(data) => data,
        Err(_) => {
            eprintln!("Chat message invalid UTF-8");
            return None;
        }
};
```
I hope it helps!

**Comment by Tails** [comment]
Does anyone know what the ```topicIds``` variable contains? Is it the topic ids when subscribing to a wildcard? Or is it the topic ids that a peer is subscribed to in total?

**Comment by SionoiS** [comment]
Test it but I'm pretty sure it's the topic the message was send on.
