### ISSUE TITLE
Update Tokio to ^1 

### ISSUE THREAD

**Issue by limeschool** [ferristseng/rust-ipfs-api#66]
Please.

**Comment by ferristseng** [comment]
Looks like Hyper supports Tokio ^1...just waiting on Actix

**Comment by limeschool** [comment]
@ferristseng The [`actix-rt`](https://crates.io/crates/actix-rt) crate now depends on Tokio ^1.2.

**Comment by devnet-io** [comment]
shame that it looks like this project has been abandoned, the maintainer is unresponsive

**Comment by ferristseng** [comment]
Been busy, but going to try to get this in soon!

Also, here's a link to my paypal account: https://www.paypal.com/paypalme/my/profile :)

**Comment by limeschool** [comment]
Hi, @ferristseng! I didn't mean to sound unappreciative, and I'm not quite sure what gave @devnet-io the impression you've abandoned this project.
I would donate to you to thank you for your work; unfortunately, I'm only seventeen years old and without an income, really. Thank you for your continued work on this crate, and I'm sorry that I'm not in a position to be of more help.

**Comment by ferristseng** [comment]
Haha, no worries! I'm just messing with you. Thanks for paying attention to my work -- I do appreciate it.
