### ISSUE TITLE
Reqwest support

### ISSUE THREAD

**Issue by SionoiS** [ferristseng/rust-ipfs-api#69]
I've been looking at reqwest and it would allow async multipart #58 and browser support. 

I don't know if it was considered before, since reqwest is built on hyper could be an easy switch.

I'll start a draft PR #70.

edit: browser support not just WASM

**Comment by ferristseng** [comment]
The only reason it wasn't supported is because at the time I started this there was only basic support for async

**Comment by ferristseng** [comment]
That being said, if Hyper supports WASM, then I think this should as well?

**Comment by SionoiS** [comment]
Well I guess WASM support is not exactly what I need and yes I believe both Hyper and Reqwest compile to WASM but what I'm after is browser support.
