### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by SionoiS** [ferristseng/rust-ipfs-api#73]
Opening this issue for tracking and to help me remember caveats.

https://github.com/seanmonstar/reqwest/issues/1141
https://github.com/seanmonstar/reqwest/pull/1151
https://github.com/seanmonstar/reqwest/pull/1020
https://github.com/seanmonstar/reqwest/pull/1013

Will have to wait for crate split #43, async multipart #58, and reqwest support #69.

**Comment by tennox** [comment]
@SionoiS 
I'm also looking to use ipfs client in wasm.
Did you find a solution?

Seems tokio is mainly used with hyper backend, so the reqwest backend should be a possible solution, no?

**Comment by tennox** [comment]
**Edit**: Found this crate which compiles successfully to wasm. Some more testing needed though :thinking:

**Comment by SionoiS** [comment]
@tennox

https://lib.rs/crates/semtexzv-ipfsapi Not async which is weird when used on other targets.

My code is at https://github.com/Defluencer/rust-defluencer/tree/develop/ipfs-api Not published though.

**Comment by tennox** [comment]
> @tennox
> 
> https://lib.rs/crates/semtexzv-ipfsapi Not async which is weird when used on other targets.

I think it [is async](https://docs.rs/semtexzv-ipfsapi/latest/src/semtexzv_ipfsapi/pubsub.rs.html#79-87) 🧐
Started forking it to add dag support...

> My code is at https://github.com/Defluencer/rust-defluencer/tree/develop/ipfs-api Not published though.

...but thanks for this it's a good reference 😎

**Comment by tennox** [comment]
The one from @semtexzv is with reqwest
https://docs.rs/semtexzv-ipfsapi/latest/src/semtexzv_ipfsapi/pubsub.rs.html#79-87 🧐

**Comment by SionoiS** [comment]
I meant to say update rust-ipfs-api to include a backend that compile to wasm.

**Comment by tennox** [comment]
Oh , now i get it!
that's actually an intruiging idea 🤔
