### ISSUE TITLE
Is there any way to set the IpfsClient::cat timeout?

### ISSUE THREAD

**Issue by zemelLeong** [ferristseng/rust-ipfs-api#83]
I try to `cat` a not exists resource. The program runs for a long time. No sign of exit.

**Comment by jmmaloney4** [comment]
You could try using [`tokio::time::timeout`](https://docs.rs/tokio/1.14.0/tokio/time/fn.timeout.html) on the future returned from the ipfs api.

**Comment by zemelLeong** [comment]
Thanks. I've achieved it.
