### ISSUE TITLE
Feature Request: Allow add_with_options to support virtual/non-existent directory structures.

### ISSUE THREAD

**Issue by iohzrd** [ferristseng/rust-ipfs-api#84]
This is something I can do using js-ipfs-http-client:

```
      const dir_obj = [
        {
          path: "some.json",
          content: JSON.stringify(object),
        },
      ];
      const add_options = {
        wrapWithDirectory: true,
      };
      const add_result = await ipfs.add(obj, add_options);

```
    
I looked into writing the equivalent with build_base_request and request_stream_json like add_path does but couldn't because they are private. 

Is there another way to do this already?
If not, I suppose I could take a swing at implementing it.
Would adding an Optional form argument be a good approach?
Something like:
```
    async fn add_with_options<R>(
        &self,
        data: R,
        add: request::Add<'_>,
        mut form_option: Option<multipart::Form<'static>>,
    ) -> Result<response::AddResponse, Self::Error>
    where
        R: 'static + Read + Send + Sync,
    {
        if form_option.is_none() {
            let mut form_unwrapped = multipart::Form::default();
            form_unwrapped.add_reader("path", data);
            form_option = Some(form_unwrapped);
        }

        self.request(add, form_option).await
    }
```

**Comment by SionoiS** [comment]
Do you know of https://github.com/ferristseng/rust-ipfs-api/blob/master/ipfs-api-prelude/src/request/add.rs

**Comment by iohzrd** [comment]
yeah, I tried it using:
```
  let json = serde_json::to_string(&p).unwrap();
  let data = Cursor::new(json);
  let add = ipfs_api::request::Add::builder()
    .wrap_with_directory(true)
    .build();
  let result = match state.ipfs_client.add_with_options(data, add).await ...
```
but there seems to be two issues...

1. when I use it, I get:
```
Parse(
    Error("trailing characters", line: 2, column: 1),
)
```
2. I couldn't find a way to define the directory structure, in the case, the "file name" for data.

Am I missing something?

**Comment by SionoiS** [comment]
About thew error I'm not sure.

But if your using json data why not use IPLD via ipfs dag put?

**Comment by iohzrd** [comment]
I've just never tried it, my current usecase is based on uploading json. Not sure IPLD would fit the usecase, but maybe it would.

**Comment by SionoiS** [comment]
I understand.

ipfs add in this case is made for file not really json constructed programatically.

If your can fix it that would be good.

**Comment by iohzrd** [comment]
I should be possible using something like the code I posted above, since that's basically how add_path already works. I'm new to rust though, so I've yet to make it work. 
currently with.
```
    #[inline]
    async fn add_with_options<R>(
        &self,
        data: R,
        add: request::Add<'_>,
        form: Option<multipart::Form<'static>>,
    ) -> Result<response::AddResponse, Error>
    where
        R: 'static + Read + Send + Sync,
    {
        let mut form_option = form;
        if form_option.is_none() {
            let mut form_unwrapped = multipart::Form::default();
            form_unwrapped.add_reader("path", data);
            form_option = Some(form_unwrapped);
        }

        self.request(add, form_option).await
    }
```
results in :    
```
hidden type for `impl Trait` captures lifetime that does not appear in boundsrustcE0700
internal.rs(466, 10): hidden type `impl futures::Future` captures lifetime smaller than the function body
```

Looked it up, but not sure how to proceed.

**Comment by iohzrd** [comment]
I'm willing to pay a small bounty for this functionality to be expedited into the next release.

**Comment by iohzrd** [comment]
Alright, I've got a working implementation here:

https://github.com/iohzrd/rust-ipfs-api/blob/e964814abc84ebc4a87bd2a2c4ffe53db71fe752/ipfs-api/src/client/internal.rs#L494

https://github.com/iohzrd/rust-ipfs-api/blob/e964814abc84ebc4a87bd2a2c4ffe53db71fe752/ipfs-api-prelude/src/api.rs#L124

thoughts?

**Comment by SionoiS** [comment]
Maybe @ferristseng could chime in. API design is not really my forte.

IMO it looks good.

**Comment by ferristseng** [comment]
Thanks! I think this looks fine. I'll take a closer look this weekend, but could you make a PR for it?

**Comment by iohzrd** [comment]
Here it is.
https://github.com/ferristseng/rust-ipfs-api/pull/86
Thanks.
